options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-north1-docker.pkg.dev/$PROJECT_ID/ocr-checker/ocr-checker:$SHORT_SHA',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-north1-docker.pkg.dev/$PROJECT_ID/ocr-checker/ocr-checker:$SHORT_SHA'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'ocr-checker',
        '--image',
        'europe-north1-docker.pkg.dev/$PROJECT_ID/ocr-checker/ocr-checker:$SHORT_SHA',
        '--region',
        'europe-west1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--service-account',
        'ocr-service-account@$PROJECT_ID.iam.gserviceaccount.com'
      ]

images:
  - 'europe-north1-docker.pkg.dev/$PROJECT_ID/ocr-checker/ocr-checker:$SHORT_SHA'
